import { IQuoteState } from '../../domain/IQuoteState';

export const initialQuoteState: IQuoteState = {
  quoteName: '',
  bagName: [],
  customerName: '',
  contactName: '',
  orderDescription: '',
  orderDate: new Date().toISOString().split('T')[0],
  bagStyle: 'Default',
  desiredDeliveryDate: '',
  openEnd: '',
  estimatedOrderQty: null,
  closedEnd: '',
  annualUsage: null,
  width: [],
  gusset: [],
  sleeveLength: [],
  gluePlateDepth: [],
  finishedLength: [],
  fabricGSM: 70,
  extrudateGSM: 21,
  fabricColor: 'White',
  fabricSupplier: 'ANDURO 1',
  specialLamination: 'No',
  outerLayerType: '',
  gsm: 19,
  layerMaterial: 'INPLASA CE',
  matteUpcharge: '',
  uvTreatment: 'No',
  stickerOrHotMelt: 'No',
  handle: 'No',
  highCOF: 'No',
  numberOfColors: '8',
  ezOpenTape: 'n/a',
  threadColor: '',
  ezOpenColor: '',
  tapeColor: '',
  specialInstructions: '',
  finalDestination: 'Gulfport',
  containerLength: "40'",
  moqKg: 500,
  adLamCharge: 0.0138,
  tapeMtsKg: 147.06,
  ezOpenTapeMtsKg: 1020.41,
  commissionPercentage: 0,
  AMSAPxToAPOrCaMexCostPercentage: 0.14,
  APPriceToCustomerPercentage: 0.08,
};

export const testQuoteState: IQuoteState = {
  quoteName: 'Quote Name',
  bagName: ['BAG 001', 'BAG 002', 'BAG 003'],
  customerName: 'Fancy Business Name',
  contactName: 'Leonardo Di Caprio',
  orderDescription: 'Large PP Bag',
  orderDate: '2022-03-27',
  bagStyle: 'Step Cut',
  desiredDeliveryDate: '2022-05-03',
  openEnd: 'Flush Cut',
  estimatedOrderQty: 100000,
  closedEnd: 'Pinch Closed',
  annualUsage: 250000,
  width: [17, 7, 16, 18],
  gusset: [4, 6, 7, 9],
  sleeveLength: [26.945, 16.96845, 15.96845],
  gluePlateDepth: [1.77, 1],
  finishedLength: [29.3, 19.3, 9.7],
  fabricGSM: 70,
  extrudateGSM: 23,
  fabricColor: 'White',
  fabricSupplier: 'ANDURO 1',
  specialLamination: 'Yes',
  outerLayerType: 'BOPP GLOSSY',
  gsm: 19,
  layerMaterial: 'CHIRIPAL TS',
  matteUpcharge: '',
  uvTreatment: 'Yes',
  stickerOrHotMelt: 'No',
  handle: 'No',
  highCOF: 'No',
  numberOfColors: '08',
  ezOpenTape: 'N/A',
  threadColor: '',
  ezOpenColor: '',
  tapeColor: '',
  specialInstructions: '',
  finalDestination: 'Gulfport',
  containerLength: "40'",
  moqKg: 500,
  adLamCharge: 0.0138,
  tapeMtsKg: 147.06,
  ezOpenTapeMtsKg: 1020.41,
  commissionPercentage: 0,
  AMSAPxToAPOrCaMexCostPercentage: 0.12,
  APPriceToCustomerPercentage: 0.08,
};
